# ============================================================
# Custom zsh helpers (single-file edition)
#
# Conventions used in docs:
# - @desc:    one-line description
# - @usage:   how to call it
# - @example: example invocation(s)
#
# Notes:
# - These are shell functions meant for interactive use.
# - Prefer returning non-zero on errors.
# ============================================================


# ============================================================
# Process / networking helpers
# ============================================================

# @desc: Kill process(es) listening on a given TCP port.
# @usage: kill-port <port>
# @example: kill-port 3000
# @example: kill-port 5173
#
# What it does:
# - Uses `lsof` to find PIDs bound to tcp:<port>
# - If found, prints the PIDs then kills them (SIGKILL via kill -9)
kill-port() {
  if [ -z "$1" ]; then
    echo "Usage: kill-port <port>"
    return 1
  fi

  # `lsof -ti` prints only PIDs, one per line
  PIDS=$(lsof -ti tcp:"$1")

  if [ -z "$PIDS" ]; then
    echo "No process is using port $1"
    return 0
  fi

  echo "Killing the following processes using port $1:"
  echo "$PIDS"

  # Force kill (SIGKILL). Consider SIGTERM first if you ever want graceful shutdown.
  echo "$PIDS" | xargs kill -9
}


# ============================================================
# Git helpers
# ============================================================

# @desc: Set local git identity (user.name/user.email) for the current repo.
# @usage: git-kalpak44
# @example: cd some-repo && git-kalpak44
#
# What it does:
# - Verifies you're inside a git work tree
# - Sets repo-local config only (does not touch global git config)
# - Prints the resulting user.* config lines
git-kalpak44() {
  if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo "❌ Not inside a git repository."
    return 1
  fi

  git config user.name "Pavel Usanli"
  git config user.email "pavel.usanli@gmail.com"

  echo "✅ Local git config set:"
  git config --local --list | grep user.
}


# ============================================================
# SSH profiles helpers
#
# Goal:
# - Maintain multiple SSH identities as "profiles" under:
#     ~/.ssh/profiles/<profile>/
# - Switch active identity by changing:
#     ~/.ssh/active_profile.conf
# - Ensure your main SSH config includes:
#     Include ~/.ssh/active_profile.conf
#
# Layout:
#   ~/.ssh/
#     config                   # your main SSH config
#     active_profile.conf      # points to the currently active profile config
#     profiles/
#       work/
#         config               # per-profile config (IdentityFile etc.)
#         id_ed25519(.pub)     # example keys (generated by ssh-new)
#       github/
#         ...
#
# Tip:
# - `ssh-help` prints a command reference.
# - Use `ssh -G host | grep identityfile` to verify which key will be used.
# ============================================================

# @desc: Print the base directory containing SSH profiles.
# @usage: ssh-profiles-dir
ssh-profiles-dir() { echo "$HOME/.ssh/profiles"; }

# @desc: Print the path to the "active profile" include file.
# @usage: ssh-active-file
ssh-active-file() { echo "$HOME/.ssh/active_profile.conf"; }


# @desc: Initialize the SSH profile system (~/.ssh/profiles + include setup).
# @usage: ssh-init
# @example: ssh-init
#
# What it does:
# - Creates ~/.ssh and ~/.ssh/profiles with correct permissions
# - Ensures ~/.ssh/config exists
# - Ensures ~/.ssh/config includes `Include ~/.ssh/active_profile.conf`
# - Creates ~/.ssh/active_profile.conf if missing
ssh-init() {
  local ssh_dir="$HOME/.ssh"
  local profiles_dir="$(ssh-profiles-dir)"
  local active_file="$(ssh-active-file)"
  local main_cfg="$ssh_dir/config"

  mkdir -p "$ssh_dir" "$profiles_dir"
  chmod 700 "$ssh_dir"

  # Ensure main config exists
  if [ ! -f "$main_cfg" ]; then
    printf "# SSH main config\n" > "$main_cfg"
  fi

  # Ensure Include line exists (idempotent)
  if ! grep -qE '^[[:space:]]*Include[[:space:]]+~/.ssh/active_profile\.conf[[:space:]]*$' "$main_cfg"; then
    printf "\n# Active SSH profile\nInclude ~/.ssh/active_profile.conf\n" >> "$main_cfg"
  fi
  chmod 600 "$main_cfg" 2>/dev/null

  # Create active file if missing
  if [ ! -f "$active_file" ]; then
    printf "# No active profile yet.\n# Use: ssh-use <profile>\n" > "$active_file"
    chmod 600 "$active_file" 2>/dev/null
    echo "✅ SSH profiles initialized. No active profile set yet."
  else
    chmod 600 "$active_file" 2>/dev/null
    echo "✅ SSH profiles already initialized."
  fi
}


# @desc: Create a new SSH profile and generate a keypair for it.
# @usage: ssh-new <profile> <algorithm>
# @example: ssh-new work rsa
# @example: ssh-new github ed25519
#
# Notes:
# - Supported algorithms: rsa | ed25519
# - Generates keys under ~/.ssh/profiles/<profile>/
# - Creates a per-profile SSH config that points Host * to the generated key
ssh-new() {
  local name="$1"
  local algo="${2:-rsa}"   # default rsa

  if [ -z "$name" ]; then
    echo "Usage: ssh-new <profile> <algorithm>"
    echo "Algorithms: rsa | ed25519"
    return 1
  fi

  if [[ ! "$name" =~ '^[A-Za-z0-9._-]+$' ]]; then
    echo "Invalid profile name: $name"
    return 1
  fi

  case "$algo" in
    rsa|ed25519)
      ;;
    *)
      echo "Unsupported algorithm: $algo"
      echo "Supported: rsa | ed25519"
      return 1
      ;;
  esac

  local profile_dir="$(ssh-profiles-dir)/$name"
  local config_path="$profile_dir/config"
  local key_path=""

  if [ -d "$profile_dir" ]; then
    echo "Profile already exists: $name"
    return 1
  fi

  mkdir -p "$profile_dir"
  chmod 700 "$profile_dir"

  echo "🔐 Generating new $algo key for profile: $name"

  if [ "$algo" = "ed25519" ]; then
    key_path="$profile_dir/id_ed25519"
    ssh-keygen -t ed25519 -a 100 -f "$key_path" -C "$USER@$HOSTNAME-$name"
  else
    key_path="$profile_dir/id_rsa"
    ssh-keygen -t rsa -b 4096 -o -a 100 -f "$key_path" -C "$USER@$HOSTNAME-$name"
  fi

  chmod 600 "$key_path"
  chmod 644 "$key_path.pub"

  # Create profile config
  cat > "$config_path" <<EOF
# Profile: $name
#
# This config is included indirectly via:
#   ~/.ssh/config -> Include ~/.ssh/active_profile.conf
#   ~/.ssh/active_profile.conf -> Include ~/.ssh/profiles/$name/config

Host *
  IdentityFile $key_path
  IdentitiesOnly yes

  # Prefer post-quantum + modern key exchange (supported by some OpenSSH builds)
  KexAlgorithms sntrup761x25519-sha512@openssh.com,curve25519-sha256

  ServerAliveInterval 60
  ServerAliveCountMax 3
EOF

  chmod 600 "$config_path"

  echo
  echo "✅ Profile created: $name"
  echo "Algorithm: $algo"
  echo "Private key: $key_path"
  echo
  echo "Public key:"
  echo "----------------------------------------"
  cat "$key_path.pub"
  echo "----------------------------------------"
  echo
}


# @desc: Remove an SSH profile directory (with safety checks).
# @usage: ssh-rm <profile>
# @usage: ssh-rm --force <profile>
# @example: ssh-rm work
# @example: ssh-rm --force github
#
# Behavior:
# - Refuses to delete the currently active profile unless --force is used
# - Prompts for confirmation before deleting
ssh-rm() {
  local force=0
  local name=""

  # Usage:
  #   ssh-rm <profile>
  #   ssh-rm --force <profile>
  if [ "$1" = "--force" ]; then
    force=1
    name="$2"
  else
    name="$1"
  fi

  if [ -z "$name" ]; then
    echo "Usage: ssh-rm [--force] <profile>"
    return 1
  fi

  if [[ ! "$name" =~ '^[A-Za-z0-9._-]+$' ]]; then
    echo "Invalid profile name: $name"
    return 1
  fi

  local profiles_dir="$(ssh-profiles-dir)"
  local profile_dir="$profiles_dir/$name"
  local active_file="$(ssh-active-file)"
  local active=""

  if [ ! -d "$profile_dir" ]; then
    echo "Profile not found: $name ($profile_dir)"
    return 1
  fi

  # Determine currently active profile by reading the Include line
  if [ -f "$active_file" ]; then
    active=$(sed -nE 's|^[[:space:]]*Include[[:space:]]+~/.ssh/profiles/([^/]+)/config[[:space:]]*$|\1|p' "$active_file")
  fi

  if [ "$name" = "$active" ] && [ "$force" -ne 1 ]; then
    echo "❌ '$name' is currently active."
    echo "Switch first: ssh-use <other-profile>"
    echo "Or force: ssh-rm --force $name"
    return 1
  fi

  echo "About to delete profile: $name"
  echo "Path: $profile_dir"
  read -q "REPLY?Are you sure? This cannot be undone. (y/N) "
  echo
  [[ "$REPLY" =~ ^[Yy]$ ]] || { echo "Aborted."; return 1; }

  # If forcing and it's active, deactivate it first
  if [ "$name" = "$active" ] && [ "$force" -eq 1 ]; then
    printf "# No active profile (profile '%s' was removed)\n# Use: ssh-use <profile>\n" "$name" > "$active_file"
    chmod 600 "$active_file" 2>/dev/null
    echo "✓ Deactivated active profile"
  fi

  rm -rf "$profile_dir"
  echo "✅ Removed profile: $name"
}


# @desc: List all SSH profiles and show which one is active.
# @usage: ssh-list
# @example: ssh-list
ssh-list() {
  local dir="$(ssh-profiles-dir)"
  local active=""

  if [ -f "$(ssh-active-file)" ]; then
    active=$(sed -nE 's|^[[:space:]]*Include[[:space:]]+~/.ssh/profiles/([^/]+)/config[[:space:]]*$|\1|p' "$(ssh-active-file)")
  fi

  if [ ! -d "$dir" ]; then
    echo "No profiles directory: $dir"
    return 1
  fi

  echo "SSH profiles in $dir:"
  for p in "$dir"/*; do
    [ -d "$p" ] || continue
    local name="$(basename "$p")"
    if [ "$name" = "$active" ]; then
      echo "  * $name (active)"
    else
      echo "    $name"
    fi
  done
}


# @desc: Activate an SSH profile (writes ~/.ssh/active_profile.conf).
# @usage: ssh-use <profile>
# @example: ssh-use work
#
# What it does:
# - Ensures ~/.ssh/config includes active_profile.conf include
# - Writes an Include line into ~/.ssh/active_profile.conf pointing to the profile config
ssh-use() {
  local name="$1"
  if [ -z "$name" ]; then
    echo "Usage: ssh-use <profile>"
    return 1
  fi

  if [[ ! "$name" =~ '^[A-Za-z0-9._-]+$' ]]; then
    echo "Invalid profile name: $name"
    return 1
  fi

  local profile_dir="$(ssh-profiles-dir)/$name"
  local profile_cfg="$profile_dir/config"
  local active_file="$(ssh-active-file)"
  local main_cfg="$HOME/.ssh/config"

  if [ ! -f "$profile_cfg" ]; then
    echo "Profile config not found: $profile_cfg"
    return 1
  fi

  mkdir -p "$HOME/.ssh"
  chmod 700 "$HOME/.ssh"

  # Ensure main config includes active profile include line (append if missing)
  if [ -f "$main_cfg" ]; then
    if ! grep -qE '^[[:space:]]*Include[[:space:]]+~/.ssh/active_profile\.conf[[:space:]]*$' "$main_cfg"; then
      printf "\nInclude ~/.ssh/active_profile.conf\n" >> "$main_cfg"
    fi
  else
    printf "Include ~/.ssh/active_profile.conf\n" > "$main_cfg"
  fi
  chmod 600 "$main_cfg" 2>/dev/null

  # Activate profile by writing include pointer (atomic-ish write)
  local tmp="${active_file}.tmp"
  printf "Include ~/.ssh/profiles/%s/config\n" "$name" > "$tmp"
  mv "$tmp" "$active_file"
  chmod 600 "$active_file" 2>/dev/null

  echo "✅ Active SSH profile: $name"
}


# @desc: Create a profile from current ~/.ssh state (copy files into a profile dir).
# @usage: ssh-snapshot <profile>
# @usage: ssh-snapshot --no-activate <profile>
# @example: ssh-snapshot work
# @example: ssh-snapshot --no-activate github
#
# Behavior:
# - Copies most files from ~/.ssh into ~/.ssh/profiles/<profile>/
# - Skips known_hosts, authorized_keys, active_profile.conf, and the profiles directory itself
# - Prompts before overwriting files inside the profile
# - Optionally activates the snapshot profile unless --no-activate is used
ssh-snapshot() {
  local profile=""
  local activate=1

  if [ "$1" = "--no-activate" ]; then
    activate=0
    profile="$2"
  else
    profile="$1"
  fi

  if [ -z "$profile" ]; then
    echo "Usage: ssh-snapshot <profile> [--no-activate]"
    return 1
  fi

  if [[ ! "$profile" =~ '^[A-Za-z0-9._-]+$' ]]; then
    echo "Invalid profile name: $profile"
    return 1
  fi

  local ssh_dir="$HOME/.ssh"
  local profiles_dir="$(ssh-profiles-dir)"
  local profile_dir="$profiles_dir/$profile"
  local main_cfg="$ssh_dir/config"
  local active_file="$(ssh-active-file)"

  if [ ! -d "$ssh_dir" ]; then
    echo "~/.ssh does not exist."
    return 1
  fi

  mkdir -p "$profiles_dir" "$profile_dir"
  chmod 700 "$ssh_dir" "$profiles_dir" "$profile_dir" 2>/dev/null

  echo "Creating SSH profile snapshot: $profile"
  echo

  # Copy current files into the profile (excluding shared/system entries)
  for f in "$ssh_dir"/*; do
    [ -e "$f" ] || continue
    local name="$(basename "$f")"

    case "$name" in
      known_hosts|authorized_keys|active_profile.conf|profiles)
        continue
        ;;
    esac

    [ -f "$f" ] || continue

    if [ -f "$profile_dir/$name" ]; then
      read -q "REPLY?$name already exists in profile. Overwrite? (y/N) "
      echo
      [[ "$REPLY" =~ ^[Yy]$ ]] || { echo "Skipping $name"; continue; }
    fi

    cp -p "$f" "$profile_dir/$name"
    echo "✓ Copied $name"
  done

  # Ensure main config includes active_profile.conf (idempotent)
  if [ -f "$main_cfg" ]; then
    if ! grep -qE '^[[:space:]]*Include[[:space:]]+~/.ssh/active_profile\.conf[[:space:]]*$' "$main_cfg"; then
      printf "\nInclude ~/.ssh/active_profile.conf\n" >> "$main_cfg"
      echo "✓ Updated ~/.ssh/config to include active_profile.conf"
    fi
  else
    printf "Include ~/.ssh/active_profile.conf\n" > "$main_cfg"
    echo "✓ Created ~/.ssh/config"
  fi
  chmod 600 "$main_cfg" 2>/dev/null

  # Tighten permissions for common private key patterns inside the profile
  chmod 600 "$profile_dir"/id_* "$profile_dir"/*.pem 2>/dev/null

  if [ "$activate" -eq 1 ]; then
    local tmp="${active_file}.tmp"
    printf "Include ~/.ssh/profiles/%s/config\n" "$profile" > "$tmp"
    mv "$tmp" "$active_file"
    chmod 600 "$active_file" 2>/dev/null
    echo
    echo "✅ Snapshot created and activated: $profile"
  else
    echo
    echo "✅ Snapshot created: $profile"
    echo "Activate with: ssh-use $profile"
  fi
}


# @desc: Print public key(s) from the currently active SSH profile.
# @usage: ssh-print-public
# @example: ssh-print-public
#
# Behavior:
# - Reads ~/.ssh/active_profile.conf to determine active profile name
# - Prints all *.pub files found under that profile directory
ssh-print-public() {
  local active_file="$(ssh-active-file)"
  local profiles_dir="$(ssh-profiles-dir)"
  local active=""

  if [ ! -f "$active_file" ]; then
    echo "No active profile file found."
    return 1
  fi

  active=$(sed -nE 's|^[[:space:]]*Include[[:space:]]+~/.ssh/profiles/([^/]+)/config[[:space:]]*$|\1|p' "$active_file")

  if [ -z "$active" ]; then
    echo "No active SSH profile."
    return 1
  fi

  local profile_dir="$profiles_dir/$active"

  if [ ! -d "$profile_dir" ]; then
    echo "Active profile directory not found: $profile_dir"
    return 1
  fi

  echo "🔐 Active SSH profile: $active"
  echo

  local found=0
  for pub in "$profile_dir"/*.pub; do
    [ -f "$pub" ] || continue
    found=1
    echo "Public key: $(basename "$pub")"
    echo "----------------------------------------"
    cat "$pub"
    echo "----------------------------------------"
    echo
  done

  if [ "$found" -eq 0 ]; then
    echo "No public keys found in $profile_dir"
    return 1
  fi
}


# @desc: Print a help/reference block for the SSH profile helper system.
# @usage: ssh-help
# @example: ssh-help
ssh-help() {
  local active=""
  local active_file="$(ssh-active-file)"

  if [ -f "$active_file" ]; then
    active=$(sed -nE 's|^[[:space:]]*Include[[:space:]]+~/.ssh/profiles/([^/]+)/config[[:space:]]*$|\1|p' "$active_file")
  fi

  echo
  echo "🔐 SSH Profile Helper System"
  echo "----------------------------------------"
  if [ -n "$active" ]; then
    echo "Active profile: $active"
  else
    echo "Active profile: (none)"
  fi
  echo

  cat <<'EOF'
Core Commands:
  ssh-init
      Initialize SSH profile system (~/.ssh/profiles + include setup)

  ssh-new <profile> <algorithm>
      Create new profile + generate key
      Algorithms: rsa | ed25519
      Examples:
        ssh-new work rsa
        ssh-new github ed25519

  ssh-snapshot <profile> [--no-activate]
      Create profile from current ~/.ssh state (copies files)

  ssh-use <profile>
      Activate a profile

  ssh-list
      List all profiles and show active one

  ssh-rm <profile>
  ssh-rm --force <profile>
      Remove a profile (won't delete active unless --force)

Key Utilities:
  ssh-print-public
      Print public key(s) from active profile

  ssh-profiles-dir
      Print profiles directory path

  ssh-active-file
      Print active profile include file path

Debug / Testing:
  ssh -v <host>
      Verbose connection debugging

  ssh -G <host> | grep identityfile
      See which key will be used

EOF
  echo
}
